-- Sembrar todas las cadenas La Santé conocidas (estatus / CSV interno)
insert into public.robin_subclientes (marca, nombre) values
  ('La Santé', 'ALAMO'),
  ('La Santé', 'ANALPER'),
  ('La Santé', 'BIGFARMA'),
  ('La Santé', 'CAMPAÑA ESOZ'),
  ('La Santé', 'CRISTALMED'),
  ('La Santé', 'FARMA EXPRESS'),
  ('La Santé', 'FARMA INFANTE NINA ROSA'),
  ('La Santé', 'FARMA INFANTE SUC EL SOMBRERO'),
  ('La Santé', 'FARMA INFANTE SUC INFANTE'),
  ('La Santé', 'FARMA INFANTE SUC INFANTE ORGANICA'),
  ('La Santé', 'FARMACIA AHINOA'),
  ('La Santé', 'FARMACIA GRUPO INSIDE'),
  ('La Santé', 'FARMACIA RUIZ PINEDA'),
  ('La Santé', 'FARMACIA RUPERTO LUGO'),
  ('La Santé', 'FARMACIA SAMÁN DE PERIJÁ'),
  ('La Santé', 'FARMACIA TIENDA PERFECTA'),
  ('La Santé', 'FARMACIA VENCEDORA'),
  ('La Santé', 'FARMACIA XXX'),
  ('La Santé', 'FARMACIA YA'),
  ('La Santé', 'FARMAECONOMICA'),
  ('La Santé', 'FARMAEXPRESS MARGARITA'),
  ('La Santé', 'FARMAGO'),
  ('La Santé', 'FARMAMIGO'),
  ('La Santé', 'FARMANUTRY'),
  ('La Santé', 'FARMATODO'),
  ('La Santé', 'FARMAX'),
  ('La Santé', 'FRANLUIS'),
  ('La Santé', 'GAMA'),
  ('La Santé', 'GRUPO PEREIRA'),
  ('La Santé', 'GRUPO TODO HOGAR'),
  ('La Santé', 'LA SANTÉ'),
  ('La Santé', 'LOCATEL'),
  ('La Santé', 'MARAPLUS'),
  ('La Santé', 'MI FARMA PF'),
  ('La Santé', 'MULTIMARCA'),
  ('La Santé', 'OTC'),
  ('La Santé', 'PROBIÓTICOS'),
  ('La Santé', 'Rattan Margarita'),
  ('La Santé', 'SAN ANSELMO'),
  ('La Santé', 'XANA')
on conflict (marca, nombre) do nothing;
